/* Generated by tools/delta-consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/frca/rules/constants.
   The lifted ones are in delta_consts_frca.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

const delta_store frca_delta_authored_store[] = {
    { 0, 0 },
};
