/* Generated by tools/gen-lang.py. Do not edit.

   itit as one table, which is the only name the engine knows it by.
   Everything below is defined by one of the generated files beside this,
   under a name carrying the language, because a program may have several
   languages in it and IBM gave the tables the same names in every module.
   src/delta_lang.h says how the engine reaches whichever is in force. */

#include "delta.h"
#include "delta_rules_c.h"
#include "delta_rules_itit.h"

extern const int32_t itit_eci_library_lang;
extern const char    itit_eci_library_name[];
extern const char    itit_eciIni[];
extern const int32_t itit_eciIniSize;
extern const int32_t itit_delta_state_bytes;

extern const int8_t              itit_delta_globals[];
extern const int32_t             itit_delta_globals_n;
extern const delta_compound_decl itit_delta_compounds[];

extern delta_stmt itit_vstmtbl[];
extern void       itit_viasizes(void);

extern void itit_link_new(delta_state *d);
extern void itit_link_delete(delta_state *d);
extern void itit_set_dict_new(delta_state *d);
extern void itit_set_dict_delete(delta_state *d);
extern void itit_act_dict_new(delta_state *d);
extern void itit_act_dict_delete(delta_state *d);

extern const delta_rule_c itit_delta_rule_native[];

extern const delta_store itit_delta_authored_store[];

extern const delta_codepoint itit_delta_codepoints[];
extern const int32_t itit_delta_codepoints_n;

/* The two slots the runtime fills in for this language: the symbol table,
   once delta_syms_bind has copied the stores into the arena, and the index
   of whichever rules are written as C. Not const, unlike everything else
   here, which is why the language holds their addresses. */
const int32_t *itit_delta_sym_ref;
delta_rule_cfn *itit_delta_native_index;

/* The five entries the engine drives a machine through are rules, so the
   shim declares each taking the machine as a value, the way every rule
   does. The engine holds a pointer, so each gets a wrapper of the shape it
   holds them in rather than a cast that would be a lie on a host where a
   pointer is wider than a value. */
extern int32_t itit_DeltaProc_start(int32_t d);
extern int32_t itit_DeltaProc_end(int32_t d);
extern int32_t itit_DeltaProc_flush(int32_t d);
extern int32_t itit_DeltaProc_process_sentences(int32_t d);
extern int32_t itit_DeltaProc_process_remaining(int32_t d);
extern int32_t itit_DeltaProc_main(int32_t d);

static int32_t proc_start(delta_state *d)
{
    return itit_DeltaProc_start(EVV_REF(d));
}

static int32_t proc_end(delta_state *d)
{
    return itit_DeltaProc_end(EVV_REF(d));
}

static int32_t proc_flush(delta_state *d)
{
    return itit_DeltaProc_flush(EVV_REF(d));
}

static int32_t proc_process_sentences(delta_state *d)
{
    return itit_DeltaProc_process_sentences(EVV_REF(d));
}

static int32_t proc_process_remaining(delta_state *d)
{
    return itit_DeltaProc_process_remaining(EVV_REF(d));
}

static int32_t proc_main(delta_state *d)
{
    return itit_DeltaProc_main(EVV_REF(d));
}


/* Not const, because the numbers below cannot go in an initialiser: each
   lives in another file as a const object, which C does not count as a
   constant expression. delta_lang_bind_itit fills them in once, before
   anything asks the language anything. */
delta_language delta_lang_itit = {
    "itit",
    "Italian",
    0, 0, 0,             /* id, library name, how big a machine is */

    itit_delta_rule_code,
    itit_delta_rule_imm,
    itit_delta_rule_map,
    itit_delta_rule_entry,
    itit_delta_rule_entry_name,
    itit_delta_rule_sym,
    0,                   /* how many of those */
    itit_delta_rules,
    0, 0,                /* how many, and which one plants a landing place */
    DELTA_RULE_FRAME_MAX,
    itit_delta_rule_native,
    &itit_delta_native_index,

    itit_delta_const_store,
    itit_delta_authored_store,
    itit_delta_codepoints,
    0,                   /* how many of those */
    &itit_delta_sym_ref,

    itit_vstmtbl,
    itit_viasizes,

    itit_delta_globals,
    0,                   /* how many */
    itit_delta_compounds,

    itit_link_new,
    itit_link_delete,
    itit_set_dict_new,
    itit_set_dict_delete,
    itit_act_dict_new,
    itit_act_dict_delete,

    proc_start,
    proc_end,
    proc_flush,
    proc_process_sentences,
    proc_process_remaining,
    proc_main,

    0, 0,                /* the settings blob and its size */
};

void delta_lang_bind_itit(void)
{
    delta_language *l = &delta_lang_itit;

    l->id             = itit_eci_library_lang;
    l->library_name   = itit_eci_library_name;
    l->state_bytes    = itit_delta_state_bytes;
    l->rule_sym_count = itit_delta_rule_sym_count;
    l->rule_count     = itit_delta_rule_count;
    l->rule_setjmp    = itit_delta_rule_setjmp;
    l->globals_n      = itit_delta_globals_n;
    l->codepoints_n   = itit_delta_codepoints_n;
    l->ini            = itit_eciIni;
    l->ini_size       = itit_eciIniSize;
}
