/* Generated by tools/lang-codepoints.py. Do not edit.

   What each of esus's own characters arrives as: the code point a caller
   writes, and the byte the machine knows it by. Out of
   lang/esus/esus.codepoints.

   The engine asks the language in force before it falls back to the one
   Windows Western list it has, which is where every character of the
   languages IBM shipped already is. */

#include <stdint.h>

#include "delta_lang.h"

/* None of its own: every character it has is in the
   Western set the engine already knows. */
const delta_codepoint esus_delta_codepoints[] = {
    { 0, 0 },
};

const int32_t esus_delta_codepoints_n = 0;
