/* Generated by tools/delta-consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/enus/rules/constants.
   The lifted ones are in delta_consts_enus.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t enus_evv_authored_data[] = {
    /* lex_prefix_re, 2 bytes at 0 */
    24,2,
};

const delta_store enus_delta_authored_store[] = {
    { enus_evv_authored_data, sizeof enus_evv_authored_data },
    { 0, 0 },
};
