/* Generated by tools/gen-lang.py. Do not edit.

   No rules of plpl written as C, so every one of them runs as bytecode.

   The interpreter looks in this table before it runs a rule and takes what
   it finds there instead. The table it looks in is either this one, which
   is empty, or the one tools/delta-decompile.py writes, which holds all of
   them. Both speak the same samples; the difference is a dozen megabytes of
   C and several minutes of compiler, so the empty one is what an ordinary
   build links and `make RULES=c' is what asks for the other. */

#include "delta_rules_c.h"

const delta_rule_c plpl_delta_rule_native[] = {
    { -1, 0 },
};
