/* Generated by tools/lang-codepoints.py. Do not edit.

   What each of plpl's own characters arrives as: the code point a caller
   writes, and the byte the machine knows it by. Out of
   lang/plpl/plpl.codepoints.

   The engine asks the language in force before it falls back to the one
   Windows Western list it has, which is where every character of the
   languages IBM shipped already is. */

#include <stdint.h>

#include "delta_lang.h"

const delta_codepoint plpl_delta_codepoints[] = {
    { 0x0105, 0x82 },
    { 0x0107, 0x83 },
    { 0x0119, 0x84 },
    { 0x0142, 0x86 },
    { 0x0144, 0x87 },
    { 0x015b, 0x88 },
    { 0x017a, 0x89 },
    { 0x017c, 0x8b },
    { 0x0104, 0x82 },
    { 0x0106, 0x83 },
    { 0x0118, 0x84 },
    { 0x0141, 0x86 },
    { 0x0143, 0x87 },
    { 0x015a, 0x88 },
    { 0x0179, 0x89 },
    { 0x017b, 0x8b },
};

const int32_t plpl_delta_codepoints_n = 16;
