#!/usr/bin/env python3
"""Lift the Delta runtime's numeric tables out of an object into C.

The tables are constants the runtime indexes, not code, so they are copied
across rather than rewritten. Each is emitted with the element width the code
actually reads it at, because a byte-for-byte copy would be read backwards on
a machine that is not little-endian.

Nothing is guessed. A table's extent comes from the next symbol in the same
section, and a table whose length is not a whole number of elements is
reported rather than emitted.
"""

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# How wide the runtime reads each table's elements, taken from the
# instructions that index them.
WIDTH = {
    "MidlineVals": 2,
    "ETI2WPM_Table": 2,
    "LnTable": 2,
    "ExpTable": 2,
    "PwindModTable": 2,
    "Mi2HzTable": 2,
    "Hz2MiTable": 2,
    "ExpTab": 2,
    "LogTab": 2,
    "SpeedTable": 2,
    # Four-byte records whose first half is the value the code reads.
    "frequencyInHz": 4,
    "frequencyInST": 4,
    "ExpTableCh0": 4,
    "ExpTableCh1": 4,
    "ExpTableCh2": 4,
}


def sections(obj):
    """Every data section's bytes, keyed by name and index."""
    out = subprocess.run(["llvm-objdump", "-s", obj],
                         check=True, capture_output=True, text=True).stdout
    result = {}
    name = None
    for line in out.splitlines():
        m = re.match(r"^Contents of section (\S+):$", line)
        if m:
            name = m.group(1)
            result.setdefault(name, bytearray())
            continue
        m = re.match(r"^\s*([0-9a-f]+)\s((?:[0-9a-f]{2,8}\s){1,4})", line)
        if m and name:
            addr = int(m.group(1), 16)
            data = bytes.fromhex(m.group(2).replace(" ", ""))
            while len(result[name]) < addr:
                result[name].append(0)
            result[name][addr:addr + len(data)] = data
    return result


def symbols(obj):
    """Data symbols as (name, section letter, offset)."""
    out = subprocess.run(["llvm-nm", obj],
                         check=True, capture_output=True, text=True).stdout
    found = []
    for line in out.splitlines():
        m = re.match(r"^([0-9a-f]+) ([dDrR]) _(\S+)$", line)
        if m:
            found.append((m.group(3), m.group(2).lower(),
                          int(m.group(1), 16)))
    return found


def emit(name, width, data):
    kind = {2: "int16_t", 4: "int32_t"}[width]
    count = len(data) // width
    print("const %s delta_%s[%d] = {" % (kind, name, count))
    row = []
    for i in range(count):
        chunk = data[i * width:(i + 1) * width]
        value = int.from_bytes(chunk, "little", signed=True)
        row.append("%6d," % value)
        if len(row) == 8:
            print("   " + " ".join(row))
            row = []
    if row:
        print("   " + " ".join(row))
    print("};")
    print()


def main():
    obj = sys.argv[1] if sys.argv[1:] else \
        os.path.join(ROOT, "analysis", "enus", "dutil.obj")

    data = sections(obj)
    letter = {"d": ".data", "r": ".rdata"}
    found = symbols(obj)

    # Each table runs to the next symbol in the same section.
    bounds = {}
    for sec in set(letter[s] for _n, s, _o in found):
        here = sorted((o, n) for n, s, o in found if letter[s] == sec)
        for i, (off, name) in enumerate(here):
            end = here[i + 1][0] if i + 1 < len(here) else len(data.get(sec, b""))
            bounds[name] = (sec, off, end)

    print("/* Generated by tools/delta-tables.py from %s. */"
          % os.path.basename(obj))
    print('#include "delta.h"')
    print()

    bad = []
    for name in sorted(bounds):
        sec, off, end = bounds[name]
        width = WIDTH.get(name)
        if width is None:
            bad.append("%s: no width recorded" % name)
            continue
        blob = bytes(data[sec][off:end])
        if len(blob) % width:
            bad.append("%s: %d bytes is not a whole number of %d-byte entries"
                       % (name, len(blob), width))
            continue
        emit(name, width, blob)

    for line in bad:
        sys.stderr.write("delta-tables: %s\n" % line)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
