#!/usr/bin/env python3
"""Bytes a rule of ours names by address.

A rule that tests text names the bytes it tests against by address, and the
address is a symbol: the emitter numbers it, the engine looks it up in the
language's symbol table, and startup has copied the bytes into the arena so
that a thirty-two bit value can name them. All of that already works for the
constants IBM compiled, which come out of its objects with the rules.

This is the same thing for constants there is no object for, which is what
writing a new rule means. The text is one to a line in `lang/<tag>/rules
/constants':

    bytes hello 48 65 6c 6c 6f
    text  stop "stop"

and what it writes is `delta_authored_<tag>.c', the one file in a language
module that no lifter touches, plus the lines in `lang/<tag>/rules/symbols'
that say where each name falls. A rule then says `sym hello' and nothing else
has to know.

The bytes are the bytes. A string a rule holds against the text being read is
not ASCII: it is one code per character in the alphabet the statement type
declares, which tools/delta-lexicon.py prints for a language. `text' is for
the ones that really are ASCII, and `bytes' is for the rest.

The bytes the rules already named have a text form here too, since a module
that cannot be built without IBM's objects is not a module anybody can author:
`<tag>.consts' is every store the rules name by address, and it is written out
of the C in the tree rather than out of the objects. That is deliberate, for the
same reason the sets are: tools/delta-dict.py appends a record to one of those
stores when a pronunciation is edited, so the objects hold what the dictionary
said before anything was added.

usage: delta-consts.py <tag>...        write each language's authored store
       delta-consts.py dump <tag>       write <tag>.consts out of the C
       delta-consts.py regenerate <tag> the C from the text against the tree
       delta-consts.py write <tag>      the C from the text, for real
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEAD = """/* Generated by tools/delta-consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/%(tag)s/rules/constants.
   The lifted ones are in delta_consts_%(tag)s.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

"""

# What the store is called, and how the symbols file says a name in it belongs
# to no object in particular: a constant of ours is the language's rather than
# one object's, so any rule may name it.
STORE = "%s_evv_authored_data"
ANY = "*"


def read_constants(path):
    """Each constant as a name and its bytes, in the order they are written."""
    out = []
    for n, raw in enumerate(open(path), 1):
        line = raw.split("#")[0].strip()
        if not line:
            continue
        w = line.split(None, 2)
        where = "%s line %d" % (os.path.basename(path), n)
        if len(w) < 3:
            raise ValueError("%s: a constant is a kind, a name and its bytes"
                             % where)
        kind, name, rest = w
        if kind == "bytes":
            try:
                data = bytes(int(b, 16) for b in rest.split())
            except ValueError:
                raise ValueError("%s: %r is not bytes in hex" % (where, rest))
        elif kind == "text":
            if not (rest.startswith('"') and rest.endswith('"')):
                raise ValueError("%s: text goes in quotes" % where)
            data = rest[1:-1].encode("ascii")
        else:
            raise ValueError("%s: no constant called %r" % (where, kind))
        if not data:
            raise ValueError("%s: %s has no bytes" % (where, name))
        out.append((name, data))
    return out


def write_store(tag, out, constants):
    """The bytes as one store, and where each name falls in it."""
    store = STORE % tag
    at = []
    body = []
    off = 0
    for name, data in constants:
        at.append((name, off))
        body.append("    /* %s, %d bytes at %d */"
                    % (name, len(data), off))
        for i in range(0, len(data), 16):
            body.append("    " + ",".join("%d" % b for b in data[i:i + 16])
                        + ",")
        off += len(data)

    with open(out, "w") as f:
        f.write(HEAD % {"tag": tag})
        if constants:
            f.write("uint8_t %s[] = {\n%s\n};\n\n" % (store, "\n".join(body)))
        f.write("const delta_store %s_delta_authored_store[] = {\n" % tag)
        if constants:
            f.write("    { %s, sizeof %s },\n" % (store, store))
        f.write("    { 0, 0 },\n};\n")
    return at


def write_symbols(path, tag, at):
    """The lines that say where an authored name falls, beside the lifted ones.

    A name of ours belongs to the language rather than to an object, so it is
    recorded against no object at all and any rule may hold it. Anything
    already recorded that way is replaced, which is what makes this safe to
    run again.
    """
    store = STORE % tag
    kept = [line.rstrip("\n") for line in open(path)
            if line.split()[:1] != ["store"] or line.split()[1] != store]
    kept = [line for line in kept
            if line.split()[:2] != ["at", ANY]]
    out = kept
    if at:
        out = out + ["", "# And the constants of our own, out of"
                         " rules/constants by tools/delta-consts.py.",
                     "store %s" % store]
        out += ["at %s %s %s %d" % (ANY, name, store, off)
                for name, off in at]
    open(path, "w").write("\n".join(out).rstrip("\n") + "\n")


# ---- the bytes the rules name, as text ---------------------------------

LIFTED_HEAD = """# Every store of bytes %(tag)s's rules name by address, as text.
#
# One `store' line to a name and then its bytes, thirty-two to a line, in the
# order the C holds them. What a rule gets is an offset into one of these, and
# lang/%(tag)s/rules/symbols is what says which store and how far in.
#
# Written by tools/delta-consts.py out of the C in the tree, not out of IBM's
# objects: a pronunciation edited through %(tag)s.dict is appended to one of
# these stores, and the objects do not have it.
"""


def lifted_path(tag):
    return os.path.join(ROOT, "lang", tag, "%s.consts" % tag)


def lifted_c(tag):
    return os.path.join(ROOT, "lang", tag, "delta_consts_%s.c" % tag)


def read_lifted_c(path):
    """Each store the C defines, in the order it defines them."""
    import re
    s = open(path).read()
    out = []
    for m in re.finditer(r"uint8_t (\w+)\[(\d+)\] = \{(.*?)\};", s, re.S):
        data = bytes(int(x) for x in m.group(3).replace("\n", "").split(",")
                     if x.strip())
        if len(data) != int(m.group(2)):
            raise ValueError("%s says %s bytes and holds %d"
                             % (m.group(1), m.group(2), len(data)))
        out.append((m.group(1), data))
    if not out:
        raise ValueError("%s defines no store" % path)
    return out


def write_lifted_text(tag, stores):
    out = [LIFTED_HEAD % {"tag": tag}]
    for name, data in stores:
        out.append("")
        out.append("store %s" % name)
        for i in range(0, len(data), 32):
            out.append("bytes %s" % " ".join("%02x" % b
                                             for b in data[i:i + 32]))
    open(lifted_path(tag), "w").write("\n".join(out) + "\n")
    return len(stores), sum(len(d) for _n, d in stores)


def read_lifted_text(path):
    stores = []
    for n, raw in enumerate(open(path), 1):
        line = raw.split("#")[0].strip()
        if not line:
            continue
        w = line.split()
        if w[0] == "store":
            stores.append([w[1], bytearray()])
        elif w[0] == "bytes":
            if not stores:
                raise SystemExit("%s line %d: bytes before any store"
                                 % (os.path.basename(path), n))
            stores[-1][1] += bytes(int(x, 16) for x in w[1:])
        else:
            raise SystemExit("%s line %d: no line called %r"
                             % (os.path.basename(path), n, w[0]))
    return [(name, bytes(data)) for name, data in stores]


def write_lifted_c(tag, stores, out):
    """The same C tools/delta-emit.py writes when it lifts these."""
    with open(out, "w") as f:
        f.write("/* Generated by tools/delta-emit.py. Do not edit.\n"
                "\n"
                "   Everything the rules name by address: the language's\n"
                "   string constants and the compiler's own, as they lie in\n"
                "   the object each was compiled into.\n"
                "\n"
                "   A pronunciation changed in lang/%s/%s.dict is appended\n"
                % (tag, tag) +
                "   here by tools/delta-dict.py, which gives the edited\n"
                "   action a record of its own rather than writing over the\n"
                "   one it had, since several actions can name the same\n"
                "   bytes. Running this lifter again puts IBM's own back\n"
                "   and loses those edits. */\n"
                "\n#include <stdint.h>\n"
                "\n#include \"delta_rules_%s.h\"\n" % tag)
        for name, data in stores:
            f.write("\nuint8_t %s[%d] = {\n" % (name, len(data)))
            for i in range(0, len(data), 16):
                f.write("    " + ",".join("%d" % b for b in data[i:i + 16])
                        + ",\n")
            f.write("};\n")
        f.write("\n/* Where each store is and how big, so that startup can\n"
                "   copy them somewhere a value can name. src/delta_syms.c is\n"
                "   the only reader: the machine holds addresses of these, and\n"
                "   an address in the program is not one a value can hold\n"
                "   unless the program was linked low, which a shared library\n"
                "   cannot be. sizeof rather than a number, so that a record\n"
                "   appended by tools/delta-dict.py is counted without this\n"
                "   table being touched. */\n")
        f.write("const delta_store %s_delta_const_store[] = {\n" % tag)
        for name, _data in stores:
            f.write("    { %s, sizeof %s },\n" % (name, name))
        f.write("    { 0, 0 },\n};\n")


def lifted_dump(tag):
    n, size = write_lifted_text(tag, read_lifted_c(lifted_c(tag)))
    print("%d stores and %d bytes in %s"
          % (n, size, os.path.relpath(lifted_path(tag), ROOT)))
    return True


def lifted_regenerate(tag, write=False):
    import tempfile
    stores = read_lifted_text(lifted_path(tag))
    if write:
        write_lifted_c(tag, stores, lifted_c(tag))
        print("%s written" % os.path.relpath(lifted_c(tag), ROOT))
        return True
    with tempfile.TemporaryDirectory() as tmp:
        made = os.path.join(tmp, "consts.c")
        write_lifted_c(tag, stores, made)
        got = open(made, "rb").read()
    want = open(lifted_c(tag), "rb").read()
    if got == want:
        print("%s: %d bytes, the same as the tree's"
              % (os.path.basename(lifted_c(tag)), len(got)))
        return True
    print("%s differs: %d bytes against %d"
          % (os.path.basename(lifted_c(tag)), len(got), len(want)))
    a, b = got.split(b"\n"), want.split(b"\n")
    for i in range(min(len(a), len(b))):
        if a[i] != b[i]:
            print("  first line that differs is %d" % (i + 1))
            print("  made: %s" % a[i][:70])
            print("  tree: %s" % b[i][:70])
            break
    return False


def one(tag):
    lang = os.path.join(ROOT, "lang", tag)
    if not os.path.isdir(lang):
        print("consts: there is no lang/%s" % tag)
        return False
    source = os.path.join(lang, "rules", "constants")
    constants = read_constants(source) if os.path.exists(source) else []
    at = write_store(tag, os.path.join(lang, "delta_authored_%s.c" % tag),
                     constants)
    symbols = os.path.join(lang, "rules", "symbols")
    if os.path.exists(symbols):
        write_symbols(symbols, tag, at)
    print("%s: %d constants, %d bytes"
          % (tag, len(constants), sum(len(d) for _n, d in constants)))
    return True


def main(argv):
    if not argv:
        print(__doc__.strip())
        return 2
    if len(argv) == 2 and argv[0] in ("dump", "regenerate", "write"):
        tag = argv[1]
        if argv[0] == "dump":
            return 0 if lifted_dump(tag) else 1
        return 0 if lifted_regenerate(tag, argv[0] == "write") else 1
    ok = True
    for tag in argv:
        try:
            ok = one(tag) and ok
        except ValueError as e:
            print("consts: %s" % e)
            ok = False
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
