#!/usr/bin/env python3
"""Emit the lookup tables sliced out of clsyn.obj as C source.

These are copied, not derived. Their last-place rounding is part of the output
we have to reproduce, so recomputing them from the formulae they approximate
would not do.
"""

import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLES = os.path.join(ROOT, "analysis", "clsyn", "tables")
OUT_C = os.path.join(ROOT, "src", "klatt_tables.c")
OUT_H = os.path.join(ROOT, "src", "klatt_tables.h")

WANTED = ["fxl2", "tl_table", "tilt8", "tilt11", "flutter_sine",
          "EX8", "CO8", "EX11", "CO11"]


# KlattSynth indexes tl_table four bytes at a time; every other table is 16 bit.
WIDE = ("tl_table",)


def load(name):
    path = os.path.join(TABLES, name + ".bin")
    with open(path, "rb") as fh:
        blob = fh.read()
    if name in WIDE:
        count = len(blob) // 4
        return struct.unpack("<%di" % count, blob[:count * 4]), len(blob), "int32_t"
    count = len(blob) // 2
    return struct.unpack("<%dh" % count, blob[:count * 2]), len(blob), "int16_t"


def main():
    print("gen-tables: reading %s" % TABLES)
    if not os.path.isdir(TABLES):
        print("gen-tables: error: run tools/catalogue.py first", file=sys.stderr)
        return 1

    banner = ("/* Generated by tools/gen-tables.py from clsyn.obj. Do not edit. */\n")

    with open(OUT_C, "w") as c, open(OUT_H, "w") as h:
        c.write(banner + "\n#include \"klatt_tables.h\"\n")
        h.write(banner + "\n#ifndef KLATT_TABLES_H\n#define KLATT_TABLES_H\n"
                "\n#include <stdint.h>\n")

        for name in WANTED:
            values, nbytes, ctype = load(name)
            sym = "klatt_" + name
            h.write("\nextern const %s %s[%d];\n" % (ctype, sym, len(values)))
            c.write("\n/* %d bytes at .rdata, read as %d signed words. */\n"
                    % (nbytes, len(values)))
            c.write("const %s %s[%d] = {\n" % (ctype, sym, len(values)))
            for i in range(0, len(values), 12):
                row = ", ".join("%8d" % v for v in values[i:i + 12])
                c.write("    " + row + ",\n")
            c.write("};\n")
            print("gen-tables: %-14s %6d bytes, %5d words"
                  % (name, nbytes, len(values)))

        h.write("\n#endif\n")

    print("gen-tables: wrote %s and %s" % (OUT_C, OUT_H))
    return 0


if __name__ == "__main__":
    sys.exit(main())
