#!/usr/bin/env python3
"""What each of a language's own characters arrives as.

The machine reads single bytes. A caller writes code points, and the engine
turns one into the other through a single Windows Western list, keeping the low
byte of everything else -- which is nothing at all for a letter outside that
set. Every language IBM shipped is inside it; Polish is not, so its letters
could be put in the alphabet and still never arrive.

`lang/<tag>/<tag>.codepoints' is where a language says what its own characters
come in as: the code point, then the byte its alphabet knows that character by.

    0105 82   # a with ogonek
    0107 83   # c with acute

`src/eci_synthtext.c` asks the language in force before it falls back to the
Western list, so a character a language names is its own business. A language
with no such file gets an empty table, which is what the eight IBM shipped
have: their letters are all in the Western set already.

The byte has to be one the alphabet claims, or the character arrives as
something else. `tools/lang-alphabet.py show <tag>` says which is which, and
this refuses a byte that alphabet does not name.

usage: lang-codepoints.py <tag>...      write each language's table
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEAD = """/* Generated by tools/lang-codepoints.py. Do not edit.

   What each of %(tag)s's own characters arrives as: the code point a caller
   writes, and the byte the machine knows it by. Out of
   lang/%(tag)s/%(tag)s.codepoints.

   The engine asks the language in force before it falls back to the one
   Windows Western list it has, which is where every character of the
   languages IBM shipped already is. */

#include <stdint.h>

#include "delta_lang.h"

"""


def text_path(tag):
    return os.path.join(ROOT, "lang", tag, "%s.codepoints" % tag)


def out_path(tag):
    return os.path.join(ROOT, "lang", tag, "delta_codepoints_%s.c" % tag)


def alphabet_bytes(tag):
    """Which byte values the language's alphabet names, so that a mapping to
    one it does not can be refused rather than heard."""
    p = os.path.join(ROOT, "lang", tag, "%s.statements" % tag)
    if not os.path.exists(p):
        return None
    inside = False
    field = None
    out = set()
    for line in open(p):
        if line.startswith("statement inp"):
            inside = True
            continue
        if line.startswith("statement ") and inside:
            break
        if not inside:
            continue
        if line.startswith("  field "):
            field = line.split()[1]
        elif line.startswith("    value") and field == "name":
            t = line[len("    value"):].rstrip("\n")
            t = t[1:] if t.startswith(" ") else t
            t = t.replace("\\s", " ").replace("\\\\", "\\")
            b = t.encode("latin-1", errors="replace")
            if len(b) == 1:
                out.add(b[0])
    return out


def read_text(path, claimed):
    out = []
    for n, raw in enumerate(open(path), 1):
        line = raw.split("#")[0].strip()
        if not line:
            continue
        w = line.split()
        where = "%s line %d" % (os.path.basename(path), n)
        if len(w) != 2:
            raise SystemExit("%s: a line is a code point and a byte" % where)
        cp = int(w[0], 16)
        byte = int(w[1], 16)
        if byte < 0 or byte > 0xff:
            raise SystemExit("%s: %02x is not a byte" % (where, byte))
        if claimed is not None and byte not in claimed:
            raise SystemExit("%s: the alphabet does not name the byte %02x,"
                             " so a character arriving as it would be"
                             " something else" % (where, byte))
        out.append((cp, byte))
    return out


def one(tag):
    lang = os.path.join(ROOT, "lang", tag)
    if not os.path.isdir(lang):
        print("codepoints: there is no lang/%s" % tag)
        return False
    source = text_path(tag)
    table = (read_text(source, alphabet_bytes(tag))
             if os.path.exists(source) else [])

    with open(out_path(tag), "w") as f:
        f.write(HEAD % {"tag": tag})
        if table:
            f.write("const delta_codepoint %s_delta_codepoints[] = {\n" % tag)
            for cp, byte in table:
                f.write("    { 0x%04x, 0x%02x },\n" % (cp, byte))
            f.write("};\n\n")
        else:
            f.write("/* None of its own: every character it has is in the\n"
                    "   Western set the engine already knows. */\n"
                    "const delta_codepoint %s_delta_codepoints[] = {\n"
                    "    { 0, 0 },\n};\n\n" % tag)
        f.write("const int32_t %s_delta_codepoints_n = %d;\n"
                % (tag, len(table)))

    print("%s: %d characters of its own" % (tag, len(table)))
    return True


def main(argv):
    if not argv:
        print(__doc__.strip())
        return 2
    ok = True
    for tag in argv:
        ok = one(tag) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
