/* Generated by tools/gen-tables.py from clsyn.obj. Do not edit. */

#ifndef KLATT_TABLES_H
#define KLATT_TABLES_H

#include <stdint.h>

extern const int16_t klatt_fxl2[20];

extern const int32_t klatt_tl_table[42];

extern const int16_t klatt_tilt8[168];

extern const int16_t klatt_tilt11[168];

extern const int16_t klatt_flutter_sine[52];

extern const int16_t klatt_EX8[3992];

extern const int16_t klatt_CO8[4991];

extern const int16_t klatt_EX11[3992];

extern const int16_t klatt_CO11[4992];

#endif
