/* Generated by tools/gen-lang.py. Do not edit.

   frfr as one table, which is the only name the engine knows it by.
   Everything below is defined by one of the generated files beside this,
   under a name carrying the language, because a program may have several
   languages in it and IBM gave the tables the same names in every module.
   src/delta_lang.h says how the engine reaches whichever is in force. */

#include "delta.h"
#include "delta_rules_c.h"
#include "delta_rules_frfr.h"

extern const int32_t frfr_eci_library_lang;
extern const char    frfr_eci_library_name[];
extern const char    frfr_eciIni[];
extern const int32_t frfr_eciIniSize;
extern const int32_t frfr_delta_state_bytes;

extern const int8_t              frfr_delta_globals[];
extern const int32_t             frfr_delta_globals_n;
extern const delta_compound_decl frfr_delta_compounds[];

extern delta_stmt frfr_vstmtbl[];
extern void       frfr_viasizes(void);

extern void frfr_link_new(delta_state *d);
extern void frfr_link_delete(delta_state *d);
extern void frfr_set_dict_new(delta_state *d);
extern void frfr_set_dict_delete(delta_state *d);
extern void frfr_act_dict_new(delta_state *d);
extern void frfr_act_dict_delete(delta_state *d);

extern const delta_rule_c frfr_delta_rule_native[];

extern const delta_store frfr_delta_authored_store[];

extern const delta_codepoint frfr_delta_codepoints[];
extern const int32_t frfr_delta_codepoints_n;

/* The two slots the runtime fills in for this language: the symbol table,
   once delta_syms_bind has copied the stores into the arena, and the index
   of whichever rules are written as C. Not const, unlike everything else
   here, which is why the language holds their addresses. */
const int32_t *frfr_delta_sym_ref;
delta_rule_cfn *frfr_delta_native_index;

/* The five entries the engine drives a machine through are rules, so the
   shim declares each taking the machine as a value, the way every rule
   does. The engine holds a pointer, so each gets a wrapper of the shape it
   holds them in rather than a cast that would be a lie on a host where a
   pointer is wider than a value. */
extern int32_t frfr_DeltaProc_start(int32_t d);
extern int32_t frfr_DeltaProc_end(int32_t d);
extern int32_t frfr_DeltaProc_flush(int32_t d);
extern int32_t frfr_DeltaProc_process_sentences(int32_t d);
extern int32_t frfr_DeltaProc_process_remaining(int32_t d);
extern int32_t frfr_DeltaProc_main(int32_t d);

static int32_t proc_start(delta_state *d)
{
    return frfr_DeltaProc_start(EVV_REF(d));
}

static int32_t proc_end(delta_state *d)
{
    return frfr_DeltaProc_end(EVV_REF(d));
}

static int32_t proc_flush(delta_state *d)
{
    return frfr_DeltaProc_flush(EVV_REF(d));
}

static int32_t proc_process_sentences(delta_state *d)
{
    return frfr_DeltaProc_process_sentences(EVV_REF(d));
}

static int32_t proc_process_remaining(delta_state *d)
{
    return frfr_DeltaProc_process_remaining(EVV_REF(d));
}

static int32_t proc_main(delta_state *d)
{
    return frfr_DeltaProc_main(EVV_REF(d));
}


/* Not const, because the numbers below cannot go in an initialiser: each
   lives in another file as a const object, which C does not count as a
   constant expression. delta_lang_bind_frfr fills them in once, before
   anything asks the language anything. */
delta_language delta_lang_frfr = {
    "frfr",
    "French",
    0, 0, 0,             /* id, library name, how big a machine is */

    frfr_delta_rule_code,
    frfr_delta_rule_imm,
    frfr_delta_rule_map,
    frfr_delta_rule_entry,
    frfr_delta_rule_entry_name,
    frfr_delta_rule_sym,
    0,                   /* how many of those */
    frfr_delta_rules,
    0, 0,                /* how many, and which one plants a landing place */
    DELTA_RULE_FRAME_MAX,
    frfr_delta_rule_native,
    &frfr_delta_native_index,

    frfr_delta_const_store,
    frfr_delta_authored_store,
    frfr_delta_codepoints,
    0,                   /* how many of those */
    &frfr_delta_sym_ref,

    frfr_vstmtbl,
    frfr_viasizes,

    frfr_delta_globals,
    0,                   /* how many */
    frfr_delta_compounds,

    frfr_link_new,
    frfr_link_delete,
    frfr_set_dict_new,
    frfr_set_dict_delete,
    frfr_act_dict_new,
    frfr_act_dict_delete,

    proc_start,
    proc_end,
    proc_flush,
    proc_process_sentences,
    proc_process_remaining,
    proc_main,

    0, 0,                /* the settings blob and its size */
};

void delta_lang_bind_frfr(void)
{
    delta_language *l = &delta_lang_frfr;

    l->id             = frfr_eci_library_lang;
    l->library_name   = frfr_eci_library_name;
    l->state_bytes    = frfr_delta_state_bytes;
    l->rule_sym_count = frfr_delta_rule_sym_count;
    l->rule_count     = frfr_delta_rule_count;
    l->rule_setjmp    = frfr_delta_rule_setjmp;
    l->globals_n      = frfr_delta_globals_n;
    l->codepoints_n   = frfr_delta_codepoints_n;
    l->ini            = frfr_eciIni;
    l->ini_size       = frfr_eciIniSize;
}
